apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlagent
  template:
    metadata:
      labels:
        app: mlagent
    spec:
      containers:
        - name: mlagent
          image: moreirar/mlagent:v2
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Always
          ports:
            - containerPort: 3000  # Port to expose on the container
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"