apiVersion: v1
kind: Service
metadata:
  name: mlagent
  labels:
    app: mlagent
    version: v2
spec:
  selector:
    app: mlagent
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer